language: python
python:
  - "2.7"
  - "3.4"
git:
  submodules: false
sudo: false  # Enables running on faster infrastructure.
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -r requirements.txt -r dev-requirements.txt
  - pip install coveralls
  - pip install pep8
script:
  - ./checkstyle.sh
  - coverage run --source sopel -m py.test .
  - coverage report --show-missing
