language: python
python:
  - "2.7"
git:
  submodules: false
sudo: false  # Enables running on faster infrastructure.
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -r dev-requirements.txt
  - pip install coveralls
  - pip install pep8
script:
  - ./checkstyle.sh
  - coverage run --source willie -m py.test .
  - coverage report --show-missing
after_success:
  coveralls
cache:
  apt: true
  directories:
    - $HOME/.cache/pip
